### ISSUE TITLE
tos 8.0.1-SNAPSHOT Could not resolve dependencies for project org.talend.studio:org.talend.designer.maven.repo.tcompv

### ISSUE THREAD

**Issue by belovanton** [Talend/studio-se-master#477]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for tos 8.0.1-SNAPSHOT:
[INFO] 
[INFO] tcommon-studio-se .................................. SUCCESS [  0.426 s]
[INFO] org.talend.libraries.apache.common ................. SUCCESS [05:08 min]
[INFO] org.talend.libraries.apache ........................ SUCCESS [02:58 min]
[INFO] org.talend.utils ................................... SUCCESS [ 52.639 s]
[INFO] org.talend.commons.runtime ......................... SUCCESS [  2.859 s]
[INFO] org.talend.cwm.mip ................................. SUCCESS [  5.772 s]
[INFO] org.talend.model ................................... SUCCESS [  3.193 s]
[INFO] org.talend.libraries.dom4j-jaxen ................... SUCCESS [  2.384 s]
[INFO] org.talend.libraries.ui ............................ SUCCESS [  0.413 s]
[INFO] org.talend.common.ui.runtime ....................... SUCCESS [  0.755 s]
[INFO] org.talend.commons.ui .............................. SUCCESS [  0.899 s]
[INFO] org.talend.libraries.csv ........................... SUCCESS [  0.147 s]
[INFO] org.talend.libraries.apache.http ................... SUCCESS [  2.468 s]
[INFO] org.talend.libraries.jackson ....................... SUCCESS [  0.157 s]
[INFO] org.talend.core.runtime ............................ SUCCESS [  6.849 s]
[INFO] Talend ESB Tooling ................................. SUCCESS [01:28 min]
[INFO] org.talend.camel.model ............................. SUCCESS [  2.549 s]
[INFO] org.talend.commons.feature ......................... SUCCESS [  0.392 s]
[INFO] tdi-studio-se ...................................... SUCCESS [  0.007 s]
[INFO] org.talend.libraries.guava ......................... SUCCESS [  2.674 s]
[INFO] org.talend.libraries.apache.cxf .................... SUCCESS [04:48 min]
[INFO] org.talend.core.repository ......................... SUCCESS [  2.796 s]
[INFO] org.talend.libraries.mdm ........................... SUCCESS [ 19.351 s]
[INFO] org.talend.metadata.managment ...................... SUCCESS [  1.607 s]
[INFO] org.talend.core .................................... SUCCESS [  0.934 s]
[INFO] org.talend.designer.maven .......................... SUCCESS [  0.878 s]
[INFO] org.talend.designer.maven.aether ................... SUCCESS [ 36.533 s]
[INFO] org.talend.libraries.apache.axis2 .................. SUCCESS [ 25.366 s]
[INFO] org.talend.libraries.apache.xml .................... SUCCESS [ 14.642 s]
[INFO] org.talend.libraries.css ........................... SUCCESS [  0.251 s]
[INFO] org.talend.libraries.excel ......................... SUCCESS [ 30.544 s]
[INFO] org.talend.libraries.hadoop.mapr.5.0.0 ............. SUCCESS [  0.516 s]
[INFO] org.talend.libraries.jboss ......................... SUCCESS [  5.119 s]
[INFO] org.talend.libraries.jdbc.h2 ....................... SUCCESS [  4.210 s]
[INFO] org.talend.libraries.jdbc.hsql ..................... SUCCESS [  0.174 s]
[INFO] org.talend.libraries.jdbc.mysql .................... SUCCESS [  0.089 s]
[INFO] org.talend.libraries.jdbc.feature .................. SUCCESS [  0.161 s]
[INFO] org.talend.libraries.jexcel ........................ SUCCESS [  0.112 s]
[INFO] org.talend.libraries.jxplorer ...................... SUCCESS [  0.190 s]
[INFO] org.talend.osgi.lib.loader ......................... SUCCESS [  0.213 s]
[INFO] org.talend.librariesmanager ........................ SUCCESS [ 28.613 s]
[INFO] org.talend.libraries.persist.lookup ................ SUCCESS [  0.255 s]
[INFO] org.talend.libraries.salesforce .................... SUCCESS [  0.297 s]
[INFO] org.talend.libraries.apache.chemistry .............. SUCCESS [  0.087 s]
[INFO] org.talend.libraries.apache.lucene ................. SUCCESS [  0.152 s]
[INFO] org.talend.libraries.custom ........................ SUCCESS [  9.957 s]
[INFO] org.talend.libraries.ehcache ....................... SUCCESS [  0.234 s]
[INFO] org.talend.libraries.groovy ........................ SUCCESS [  0.191 s]
[INFO] org.talend.libraries.javacsv ....................... SUCCESS [  0.144 s]
[INFO] org.talend.libraries.jax ........................... SUCCESS [  0.279 s]
[INFO] org.talend.libraries.mondrian ...................... SUCCESS [  0.240 s]
[INFO] org.talend.libraries.netsuite ...................... SUCCESS [  0.185 s]
[INFO] org.talend.libraries.palo .......................... SUCCESS [  0.102 s]
[INFO] org.talend.libraries.servlet ....................... SUCCESS [  0.114 s]
[INFO] org.talend.libraries.slf4j ......................... SUCCESS [  0.041 s]
[INFO] org.talend.libraries.xml ........................... SUCCESS [  9.233 s]
[INFO] org.talend.libraries.zmq ........................... SUCCESS [  2.967 s]
[INFO] org.talend.tos.libraries.feature ................... SUCCESS [  1.376 s]
[INFO] org.talend.platform.logging ........................ SUCCESS [  0.443 s]
[INFO] org.talend.utils.feature ........................... SUCCESS [  0.353 s]
[INFO] org.talend.themes.core ............................. SUCCESS [  0.887 s]
[INFO] org.talend.core.ui ................................. SUCCESS [ 17.646 s]
[INFO] org.talend.cwm.mip.edit ............................ SUCCESS [  0.888 s]
[INFO] org.talend.datatools.xml ........................... SUCCESS [  0.568 s]
[INFO] org.talend.librariesmanager.ui ..................... SUCCESS [  0.792 s]
[INFO] org.talend.maven.resolver .......................... SUCCESS [  0.158 s]
[INFO] org.talend.metadata.managment.ui ................... SUCCESS [  1.101 s]
[INFO] org.talend.migrationTool ........................... SUCCESS [  0.649 s]
[INFO] org.talend.model.edit .............................. SUCCESS [  0.884 s]
[INFO] org.talend.resources ............................... SUCCESS [  0.881 s]
[INFO] org.talend.core.feature ............................ SUCCESS [  1.148 s]
[INFO] tbd-studio-se ...................................... SUCCESS [  0.023 s]
[INFO] org.talend.demo.bigdata.ce ......................... SUCCESS [  0.278 s]
[INFO] org.talend.designer.abstractmap .................... SUCCESS [  0.883 s]
[INFO] org.talend.registration ............................ SUCCESS [  0.944 s]
[INFO] org.talend.repository.view ......................... SUCCESS [  1.063 s]
[INFO] org.talend.repository.items.importexport ........... SUCCESS [  0.835 s]
[INFO] org.talend.repository.items.importexport.ui ........ SUCCESS [  0.629 s]
[INFO] org.talend.repository .............................. SUCCESS [  3.375 s]
[INFO] org.talend.libraries.uniserv ....................... SUCCESS [  0.272 s]
[INFO] org.talend.hadoop.distribution ..................... SUCCESS [  1.997 s]
[INFO] org.talend.designer.core ........................... SUCCESS [  3.930 s]
[INFO] org.talend.hadoop.distribution.custom .............. SUCCESS [  0.290 s]
[INFO] org.talend.designer.core.generic ................... SUCCESS [  1.167 s]
[INFO] org.talend.updates.runtime ......................... SUCCESS [  1.098 s]
[INFO] org.talend.designer.codegen ........................ SUCCESS [  1.318 s]
[INFO] org.talend.designer.alfrescooutput ................. SUCCESS [  0.915 s]
[INFO] org.talend.designer.components.bigdata ............. SUCCESS [  2.235 s]
[INFO] org.talend.libraries.mozilla ....................... SUCCESS [  0.290 s]
[INFO] org.talend.designer.components.exchange ............ SUCCESS [  1.556 s]
[INFO] org.talend.libraries.jboss.jars .................... SUCCESS [  0.534 s]
[INFO] org.talend.designer.components.localprovider ....... SUCCESS [ 10.734 s]
[INFO] org.talend.designer.rowgenerator ................... SUCCESS [  0.863 s]
[INFO] org.talend.designer.runtime.visualization .......... SUCCESS [  1.476 s]
[INFO] org.talend.designer.runprocess ..................... SUCCESS [  1.709 s]
[INFO] org.talend.expressionbuilder ....................... SUCCESS [  1.341 s]
[INFO] org.talend.designer.dbmap .......................... SUCCESS [  1.713 s]
[INFO] org.talend.designer.documentation .................. SUCCESS [  1.072 s]
[INFO] org.talend.libraries.esb ........................... SUCCESS [16:10 min]
[INFO] Talend Designer ESB Tooling REST Service consumer plugin SUCCESS [  1.178 s]
[INFO] org.talend.designer.camel.dependencies.core ........ SUCCESS [  0.565 s]
[INFO] org.talend.designer.maven.ui ....................... SUCCESS [  0.708 s]
[INFO] org.talend.designer.camel.resource.core ............ SUCCESS [  0.760 s]
[INFO] org.talend.designer.publish.core ................... SUCCESS [  1.176 s]
[INFO] org.talend.camel.designer .......................... SUCCESS [  2.989 s]
[INFO] org.talend.repository.view.di ...................... SUCCESS [  1.217 s]
[INFO] org.talend.repository.services ..................... SUCCESS [  2.088 s]
[INFO] Talend Designer ESB Tooling web service consumer plugin SUCCESS [  1.401 s]
[INFO] org.talend.designer.esb.routines ................... SUCCESS [  0.524 s]
[INFO] org.talend.designer.maven.job ...................... SUCCESS [  0.521 s]
[INFO] org.talend.designer.runtime.visualization.tools .... SUCCESS [  0.364 s]
[INFO] org.talend.libraries.sqlbuilder .................... SUCCESS [  0.084 s]
[INFO] org.talend.sqlbuilder .............................. SUCCESS [  1.257 s]
[INFO] org.talend.designer.feature ........................ SUCCESS [  0.694 s]
[INFO] org.talend.designer.filemultischemas ............... SUCCESS [  1.088 s]
[INFO] org.talend.designer.fileoutputxml .................. SUCCESS [  1.156 s]
[INFO] org.talend.designer.gefabstractmap ................. SUCCESS [  0.881 s]
[INFO] org.talend.designer.hdfsbrowse ..................... SUCCESS [  1.563 s]
[INFO] org.talend.designer.mapper ......................... SUCCESS [  1.323 s]
[INFO] org.talend.designer.maven.repo.tck ................. SUCCESS [ 24.509 s]
[INFO] org.talend.designer.maven.repo.tcksdk .............. SUCCESS [02:41 min]
[INFO] org.talend.designer.maven.repo.tcompv0 ............. FAILURE [ 20.447 s]
[INFO] studio-maven-repository-tos ........................ SKIPPED
[INFO] studio-maven-repository-unzip ...................... SKIPPED
[INFO] studio-components-dependencies ..................... SKIPPED
[INFO] studio-tcompv1-dependencies ........................ SKIPPED
[INFO] studio-tacokit-dependencies ........................ SKIPPED
[INFO] studio-surefire-dependencies ....................... SKIPPED
[INFO] studio-log4j-dependencies-tos ...................... SKIPPED
[INFO] studio-maven-repository-build ...................... SKIPPED
[INFO] maven-bundle-plugin-5-1-1-tos ...................... SKIPPED
[INFO] maven-install-plugin-2-5-2-tos ..................... SKIPPED
[INFO] talend-compiler-plugin-tos ......................... SKIPPED
[INFO] build-helper-maven-plugin-3-0-0-tos ................ SKIPPED
[INFO] karaf-maven-plugin-4-2-10-tos ...................... SKIPPED
[INFO] talend-ci-osgihelper-maven-plugin-tos .............. SKIPPED
[INFO] studio-maven-repository-zip ........................ SKIPPED
[INFO] org.talend.designer.maven.tos ...................... SKIPPED
[INFO] org.talend.designer.neo4j .......................... SKIPPED
[INFO] org.talend.designer.scd ............................ SKIPPED
[INFO] org.talend.designer.tutorials ...................... SKIPPED
[INFO] org.talend.designer.unifiedcomponent ............... SKIPPED
[INFO] org.talend.designer.webservice ..................... SKIPPED
[INFO] org.talend.designer.xmlmap ......................... SKIPPED
[INFO] org.talend.esb.tooling.ws.consumer.feature ......... SKIPPED
[INFO] org.talend.hadoop.distribution.cdh6x ............... SKIPPED
[INFO] org.talend.hadoop.distribution.cdp ................. SKIPPED
[INFO] org.talend.hadoop.distribution.dbr550 .............. SKIPPED
[INFO] org.talend.hadoop.distribution.dbr640 .............. SKIPPED
[INFO] org.talend.hadoop.distribution.dbr73x .............. SKIPPED
[INFO] org.talend.hadoop.distribution.emr5290 ............. SKIPPED
[INFO] org.talend.hadoop.distribution.emr62x .............. SKIPPED
[INFO] org.talend.hadoop.distribution.synapse ............. SKIPPED
[INFO] org.talend.hadoop.distribution.hdinsight400 ........ SKIPPED
[INFO] org.talend.hadoop.distribution.hdpx ................ SKIPPED
[INFO] org.talend.spark.distribution.spark30x ............. SKIPPED
[INFO] org.talend.spark.distribution.spark24x ............. SKIPPED
[INFO] org.talend.spark.distribution.spark31x ............. SKIPPED
[INFO] org.talend.hadoop.distribution.feature ............. SKIPPED
[INFO] org.talend.help.external ........................... SKIPPED
[INFO] org.talend.help.feature ............................ SKIPPED
[INFO] org.talend.libraries.hadoop ........................ SKIPPED
[INFO] org.talend.libraries.jexcel.jars ................... SKIPPED
[INFO] org.talend.presentation.onboarding ................. SKIPPED
[INFO] org.talend.presentation.onboarding.resource ........ SKIPPED
[INFO] org.talend.presentation.onboarding.resource.tos .... SKIPPED
[INFO] org.talend.rcp ..................................... SKIPPED
[INFO] org.talend.rcp.branding.tos.bigdata ................ SKIPPED
[INFO] org.talend.repository.metadata ..................... SKIPPED
[INFO] org.talend.repository.hadoopcluster.configurator ... SKIPPED
[INFO] org.talend.repository.hadoopcluster ................ SKIPPED
[INFO] org.talend.repository.hbaseprovider ................ SKIPPED
[INFO] org.talend.repository.hcatalog ..................... SKIPPED
[INFO] org.talend.repository.hdfs ......................... SKIPPED
[INFO] org.talend.repository.maprdbprovider ............... SKIPPED
[INFO] org.talend.repository.nosql ........................ SKIPPED
[INFO] org.talend.sdk.component.studio-integration ........ SKIPPED
[INFO] org.talend.studio.components.bd.cosmosdb ........... SKIPPED
[INFO] org.talend.studio.components.bd.cosmosdb.feature ... SKIPPED
[INFO] org.talend.studio.components.bd.couchbase .......... SKIPPED
[INFO] org.talend.studio.components.bd.couchbase.feature .. SKIPPED
[INFO] org.talend.studio.components.tcompv0.couchbase ..... SKIPPED
[INFO] org.talend.studio.components.tcompv0.couchbase.feature SKIPPED
[INFO] org.talend.studio.components.tcompv0.marklogic ..... SKIPPED
[INFO] org.talend.studio.components.tcompv0.marklogic.feature SKIPPED
[INFO] org.talend.tos.bigdata.feature ..................... SKIPPED
[INFO] org.talend.libraries.couchdb ....................... SKIPPED
[INFO] org.talend.libraries.neo4j ......................... SKIPPED
[INFO] org.talend.tos.bigdata.libraries.feature ........... SKIPPED
[INFO] org.talend.rcp.feature ............................. SKIPPED
[INFO] org.talend.repository.localprovider ................ SKIPPED
[INFO] org.talend.repository.feature ...................... SKIPPED
[INFO] org.talend.repository.ftp .......................... SKIPPED
[INFO] org.talend.repository.generic ...................... SKIPPED
[INFO] org.talend.libraries.json .......................... SKIPPED
[INFO] org.talend.repository.json ......................... SKIPPED
[INFO] org.talend.repository.mdm .......................... SKIPPED
[INFO] org.talend.studio.components.tcompv0.azurestorage .. SKIPPED
[INFO] org.talend.studio.components.tcompv0.azurestorage.feature SKIPPED
[INFO] org.talend.studio.components.tcompv0.googledrive ... SKIPPED
[INFO] org.talend.studio.components.tcompv0.googledrive.feature SKIPPED
[INFO] org.talend.studio.components.tcompv0.jdbc .......... SKIPPED
[INFO] org.talend.studio.components.tcompv0.jdbc.feature .. SKIPPED
[INFO] org.talend.studio.components.tcompv0.jira .......... SKIPPED
[INFO] org.talend.studio.components.tcompv0.jira.feature .. SKIPPED
[INFO] org.talend.studio.components.tcompv0.marketo ....... SKIPPED
[INFO] org.talend.studio.components.tcompv0.marketo.feature SKIPPED
[INFO] org.talend.studio.components.tcompv0.netsuite ...... SKIPPED
[INFO] org.talend.studio.components.tcompv0.netsuite.feature SKIPPED
[INFO] org.talend.studio.components.tcompv0.salesforce .... SKIPPED
[INFO] org.talend.studio.components.tcompv0.salesforce.feature SKIPPED
[INFO] org.talend.studio.components.tcompv0.snowflake ..... SKIPPED
[INFO] org.talend.studio.components.tcompv0.snowflake.feature SKIPPED
[INFO] org.talend.studio.components.tcompv0.splunk ........ SKIPPED
[INFO] org.talend.studio.components.tcompv0.splunk.feature  SKIPPED
[INFO] org.talend.tos.components.feature .................. SKIPPED
[INFO] org.talend.updates.feature ......................... SKIPPED
[INFO] org.talend.tos.core.feature ........................ SKIPPED
[INFO] org.talend.tos.feature ............................. SKIPPED
[INFO] org.talend.themes.css.talend ....................... SKIPPED
[INFO] org.talend.rcp.branding.tos.bigdata.feature ........ SKIPPED
[INFO] org.talend.studio.tos.bigdata.product .............. SKIPPED
[INFO] org.talend.rcp.branding.tos ........................ SKIPPED
[INFO] org.talend.rcp.branding.tos.feature ................ SKIPPED
[INFO] org.talend.studio.tos.di.product ................... SKIPPED
[INFO] tdq-studio-se ...................................... SKIPPED
[INFO] org.eclipse.nebula.widgets.grid .................... SKIPPED
[INFO] org.talend.dataquality.matching .................... SKIPPED
[INFO] org.talend.libraries.google.libphonumber ........... SKIPPED
[INFO] org.talend.libraries.mapdb ......................... SKIPPED
[INFO] org.talend.libraries.clearspring.analytics ......... SKIPPED
[INFO] org.talend.dataquality ............................. SKIPPED
[INFO] org.talend.libraries.jung .......................... SKIPPED
[INFO] org.talend.libraries.jfreechart .................... SKIPPED
[INFO] org.talend.dataprofiler.service .................... SKIPPED
[INFO] org.talend.cwm.management .......................... SKIPPED
[INFO] org.talend.cwm.compare ............................. SKIPPED
[INFO] org.talend.dataprofiler.common.ui .................. SKIPPED
[INFO] org.talend.dataprofiler.help ....................... SKIPPED
[INFO] org.talend.dataquality.edit ........................ SKIPPED
[INFO] org.talend.dataprofiler.ecos ....................... SKIPPED
[INFO] org.talend.dataquality.record.linkage.ui ........... SKIPPED
[INFO] org.talend.dataprofiler.migration .................. SKIPPED
[INFO] org.talend.dataprofiler.core ....................... SKIPPED
[INFO] org.talend.cwm.compare.ui .......................... SKIPPED
[INFO] org.talend.dataprofiler.rcp ........................ SKIPPED
[INFO] org.talend.rcp.branding.top ........................ SKIPPED
[INFO] org.talend.libraries.google.re2j ................... SKIPPED
[INFO] org.talend.top.libraries.feature ................... SKIPPED
[INFO] org.talend.top.feature ............................. SKIPPED
[INFO] org.talend.update.p2.feature ....................... SKIPPED
[INFO] org.talend.rcp.branding.top.feature ................ SKIPPED
[INFO] org.talend.studio.tos.dq.product ................... SKIPPED
[INFO] org.talend.camel.designer.codegen .................. SKIPPED
[INFO] Talend Designer ESB Tooling Route components plugin  SKIPPED
[INFO] org.talend.repository.resource ..................... SKIPPED
[INFO] org.talend.designer.camel.resource ................. SKIPPED
[INFO] org.talend.designer.esb.components.router .......... SKIPPED
[INFO] org.talend.repository.view.route ................... SKIPPED
[INFO] org.talend.resources.export.route .................. SKIPPED
[INFO] org.talend.camel.designer.feature .................. SKIPPED
[INFO] org.talend.camel.core.feature ...................... SKIPPED
[INFO] org.talend.camel.feature ........................... SKIPPED
[INFO] Talend Designer ESB Tooling REST Service provider plugin SKIPPED
[INFO] Talend Designer ESB Tooling Web Service provider plugin SKIPPED
[INFO] org.talend.esb.tooling.ws.provider.feature ......... SKIPPED
[INFO] org.talend.esb.tooling.rs.provider.feature ......... SKIPPED
[INFO] org.talend.esb.tooling.feature ..................... SKIPPED
[INFO] org.talend.repository.services.feature ............. SKIPPED
[INFO] org.talend.esbstandard.feature ..................... SKIPPED
[INFO] org.talend.rcp.branding.esbstandard ................ SKIPPED
[INFO] org.talend.rcp.branding.esbstandard.feature ........ SKIPPED
[INFO] org.talend.studio.tos.esb.product .................. SKIPPED
[INFO] tos-product-aggregator-pom ......................... SKIPPED
[INFO] org.talend.bigdata.se.test.base .................... SKIPPED
[INFO] org.talend.hadoop.distribution.test.base ........... SKIPPED
[INFO] org.talend.hadoop.distribution.test ................ SKIPPED
[INFO] org.talend.hadoop.distribution.hdinsight400.test ... SKIPPED
[INFO] org.talend.repository.nosql.test ................... SKIPPED
[INFO] org.talend.hadoop.distribution.custom.test ......... SKIPPED
[INFO] org.talend.repository.hadoopcluster.test ........... SKIPPED
[INFO] org.talend.repository.hadoopcluster.configurator.test SKIPPED
[INFO] org.talend.repository.maprdbprovider.test .......... SKIPPED
[INFO] org.talend.hadoop.distribution.synapse.test ........ SKIPPED
[INFO] org.talend.repository.hdfs.test .................... SKIPPED
[INFO] org.talend.hadoop.distribution.dbr550.test ......... SKIPPED
[INFO] org.talend.hadoop.distribution.dbr73x.test ......... SKIPPED
[INFO] org.talend.hadoop.distribution.dbr640.test ......... SKIPPED
[INFO] org.talend.hadoop.distribution.emr5290.test ........ SKIPPED
[INFO] org.talend.bigdata.se.test.feature ................. SKIPPED
[INFO] org.talend.developpement ........................... SKIPPED
[INFO] org.talend.libraries.jfreechart.jars ............... SKIPPED
[INFO] org.talend.libraries.javacsv.jars .................. SKIPPED
[INFO] org.talend.libraries.apache.lucene8 ................ SKIPPED
[INFO] org.talend.fragment.jars.common.feature ............ SKIPPED
[INFO] org.talend.cwm.mip.editor .......................... SKIPPED
[INFO] org.talend.helpers ................................. SKIPPED
[INFO] org.talend.repository.view.example ................. SKIPPED
[INFO] org.talend.testutils ............................... SKIPPED
[INFO] org.talend.commons.runtime.test .................... SKIPPED
[INFO] org.talend.commons.ui.test ......................... SKIPPED
[INFO] org.talend.core.repository.test .................... SKIPPED
[INFO] org.talend.core.runtime.test ....................... SKIPPED
[INFO] org.talend.core.test ............................... SKIPPED
[INFO] org.talend.core.ui.test ............................ SKIPPED
[INFO] org.talend.libraries.javacsv.test .................. SKIPPED
[INFO] org.talend.librariesmanager.test ................... SKIPPED
[INFO] org.talend.librariesmanager.ui.test ................ SKIPPED
[INFO] org.talend.metadata.managment.test ................. SKIPPED
[INFO] org.talend.metadata.managment.ui.test .............. SKIPPED
[INFO] org.talend.migrationTool.test ...................... SKIPPED
[INFO] org.talend.model.test .............................. SKIPPED
[INFO] org.talend.repository.items.importexport.test ...... SKIPPED
[INFO] org.talend.repository.items.importexport.ui.test ... SKIPPED
[INFO] org.talend.repository.localprovider.test ........... SKIPPED
[INFO] org.talend.repository.metadata.test ................ SKIPPED
[INFO] org.talend.repository.view.test .................... SKIPPED
[INFO] org.talend.updates.runtime.test .................... SKIPPED
[INFO] org.talend.utils.test .............................. SKIPPED
[INFO] org.talend.designer.maven.test ..................... SKIPPED
[INFO] test.all.test.suite ................................ SKIPPED
[INFO] org.talend.datatools.xml.test ...................... SKIPPED
[INFO] org.talend.gmf.feature ............................. SKIPPED
[INFO] org.talend.designer.oas ............................ SKIPPED
[INFO] org.talend.libraries.microsoft ..................... SKIPPED
[INFO] org.talend.libraries.edifact ....................... SKIPPED
[INFO] org.talend.libraries.ftp ........................... SKIPPED
[INFO] org.talend.libraries.sqlbuilder.jars ............... SKIPPED
[INFO] org.talend.fragment.jars.di.feature ................ SKIPPED
[INFO] org.talend.designer.codegen.test ................... SKIPPED
[INFO] org.talend.designer.components.localprovider.test .. SKIPPED
[INFO] org.talend.designer.core.generic.test .............. SKIPPED
[INFO] org.talend.designer.core.test ...................... SKIPPED
[INFO] org.talend.designer.dbmap.test ..................... SKIPPED
[INFO] org.talend.designer.mapper.test .................... SKIPPED
[INFO] org.talend.designer.rowgenerator.test .............. SKIPPED
[INFO] org.talend.designer.runprocess.test ................ SKIPPED
[INFO] org.talend.designer.scd.test ....................... SKIPPED
[INFO] org.talend.designer.unifiedcomponent.test .......... SKIPPED
[INFO] org.talend.designer.webservice.test ................ SKIPPED
[INFO] org.talend.designer.xmlmap.test .................... SKIPPED
[INFO] org.talend.repository.generic.test ................. SKIPPED
[INFO] org.talend.repository.test ......................... SKIPPED
[INFO] org.talend.repository.view.di.test ................. SKIPPED
[INFO] org.talend.sdk.component.studio-integration.test ... SKIPPED
[INFO] org.talend.rcp.branding.tos.test.feature ........... SKIPPED
[INFO] org.talend.designer.components.libs ................ SKIPPED
[INFO] org.talend.designer.mapper.advanced ................ SKIPPED
[INFO] org.talend.libraries.w3c ........................... SKIPPED
[INFO] org.talend.expressionbuilder.test .................. SKIPPED
[INFO] net.sourceforge.sqlexplorer ........................ SKIPPED
[INFO] org.talend.dataprofiler.top.chart .................. SKIPPED
[INFO] org.talend.fragment.jars.dq.feature ................ SKIPPED
[INFO] org.talend.dataquality.standardization.migration ... SKIPPED
[INFO] test.myudi ......................................... SKIPPED
[INFO] org.talend.cwm.compare.test ........................ SKIPPED
[INFO] org.talend.cwm.management.test ..................... SKIPPED
[INFO] org.talend.dataprofiler.core.test .................. SKIPPED
[INFO] org.talend.dataprofiler.ecos.test .................. SKIPPED
[INFO] org.talend.dataquality.matching.test ............... SKIPPED
[INFO] org.talend.dataquality.record.linkage.ui.test ...... SKIPPED
[INFO] org.talend.dataquality.test ........................ SKIPPED
[INFO] org.talend.dataquality.se.test.feature ............. SKIPPED
[INFO] org.talend.esb.camel.designer.codegen.test ......... SKIPPED
[INFO] org.talend.esb.camel.designer.test ................. SKIPPED
[INFO] org.talend.esb.designer.camel.dependencies.core.test SKIPPED
[INFO] org.talend.esb.designer.camel.resource.core.test ... SKIPPED
[INFO] org.talend.esb.designer.esb.routines.test .......... SKIPPED
[INFO] org.talend.esb.repository.services.test ............ SKIPPED
[INFO] org.talend.esb.repository.view.route.test .......... SKIPPED
[INFO] org.talend.esb.tooling.test.feature ................ SKIPPED
[INFO] tos ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42:59 min
[INFO] Finished at: 2021-10-04T06:31:42Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.talend.designer.maven.repo.tcompv0: Could not resolve dependencies for project org.talend.studio:org.talend.designer.maven.repo.tcompv0:eclipse-plugin:8.0.1-SNAPSHOT: Failed to collect dependencies at org.talend.daikon-ee:format-detection-csv:jar:3.2.0: Failed to read artifact descriptor for org.talend.daikon-ee:format-detection-csv:jar:3.2.0: Could not transfer artifact org.talend.daikon-ee:format-detection-csv:pom:3.2.0 from/to releases (https://artifacts-zl.talend.com/nexus/content/repositories/releases/): Authentication failed for https://artifacts-zl.talend.com/nexus/content/repositories/releases/org/talend/daikon-ee/format-detection-csv/3.2.0/format-detection-csv-3.2.0.pom 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.talend.designer.maven.repo.tcompv0

**Comment by coheigea** [comment]
Fixed since February

**Comment by JeanCazaux** [comment]
I'd try to build "maintenance/8.0_root" branche but this error appear :
" Could not resolve dependencies for project org.talend.studio:org.talend.designer.maven.repo.tcompv0:eclipse-plugin:8.0.1: Failed to collect dependencies at org.talend.daikon-ee:format-detection-csv:jar:3.2.0"

Wich branche could be build with no error ?

**Comment by JeanCazaux** [comment]
same error on "release/8.0.1M12" branche :
[INFO] org.talend.designer.maven.repo.tcompv0 8.0.1-M12 ... FAILURE [  4.889 s]

Failed to execute goal on project org.talend.designer.maven.repo.tcompv0: Could not resolve dependencies for project org.talend.studio:org.talend.designer.maven.repo.tcompv0:eclipse-plugin:8.0.1-M12: Failed to collect dependencies at org.talend.daikon-ee:format-detection-csv:jar:3.2.0: Failed to read artifact descriptor for org.talend.daikon-ee:format-detection-csv:jar:3.2.0: The following artifacts could not be resolved: org.talend.daikon-ee:format-detection-csv:pom:3.2.0 (absent): Could not transfer artifact org.talend.daikon-ee:format-detection-csv:pom:3.2.0 from/to releases (https://artifacts-zl.talend.com/nexus/content/repositories/releases/): status code: 401, reason phrase: Unauthorized (401)
