### ISSUE TITLE
Could you please confirm branches of talend repositories in Github?.

### ISSUE THREAD

**Issue by yongan20151117** [Talend/studio-se-master#542]
I am a developer who prefer talend open studio to process the data. 
A month ago I started building the talend from git repository and tried release 7.1.1, 7.2.1, 7.4.1, 8.0.1.
However, I got only errors. I think issue is my skills, but I want that talend community provides the friendly guide document for building.

*******************************************************************************************************************************************

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (copy-studio-index) on project org.talend.librariesmanager: Unable to resolve artifact.: Could not transfer artifact org.talend.studio:studioIndex:zip:8.0.1-SNAPSHOT from/to snapshots (https://artifacts-oss.talend.com/nexus/content/repositories/snapshots/): authentication failed for https://artifacts-oss.talend.com/nexus/content/repositories/snapshots/org/talend/studio/studioIndex/8.0.1-SNAPSHOT/studioIndex-8.0.1-SNAPSHOT.zip, status: 401 Unauthorized
[ERROR]   org.talend.studio:studioIndex:zip:8.0.1-SNAPSHOT

*******************************************************************************************************************************************

**Comment by stano** [comment]
I had same problem.
I tried compile tesb-studio-se from latest master and I got this error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (copy-studio-index) on project org.talend.librariesmanager: Unable to resolve artifact.: Could not transfer artifact org.talend.studio:studioIndex:zip:8.8.8-SNAPSHOT from/to snapshots (https://artifacts-oss.talend.com/nexus/content/repositories/snapshots/): Not authorized , ReasonPhrase:Unauthorized.

The I tried older verified tag patch/8.0.1/R2022-03 with nearli same error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (copy-studio-index) on project org.talend.librariesmanager: Unable to resolve artifact.: Could not transfer artifact org.talend.studio:studioIndex:zip:8.0.1-SNAPSHOT from/to snapshots (https://artifacts-oss.talend.com/nexus/content/repositories/snapshots/): Not authorized , ReasonPhrase:Unauthorized.

Why nexus repository https://artifacts-oss.talend.com/nexus/content/repositories/snapshots/ needs login?
_Access Denied
Please [login](https://artifacts-oss.talend.com/nexus) before attempting further requests._

**Comment by vladoklimo** [comment]
Same issue ... @dkulp @undx @coheigea could you maybe give us some insight what could be wrong ?
Thanks for your time.

**Comment by eguillossou** [comment]
I'm not an expert but it seems that repo have been modified internally. https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot/ and https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceRelease/ are now used.

**Comment by coheigea** [comment]
I think this has been fixed since the end of April
