### ISSUE TITLE
toem-studio-se

### ISSUE THREAD

**Issue by stano** [Talend/studio-se-master#594]
Toem studio se referenced here
https://github.com/Talend/studio-se-master/blob/7894864ea979f052f2ac2eab91bfd44bd57fc9f4/.gitslave#L7
does not exists on github.
It is necessary for compilation of tesb-studio-se?

**Comment by bhe-talendbj** [comment]
https://github.com/Talend/toem-studio-se exits in github.

I can compile tos products without problems.

`[INFO] tmdm-common ........................................ SUCCESS [  0.002 s]
[INFO] org.talend.mdm.commmon ............................. SUCCESS [  0.412 s]
[INFO] tmdm-studio-se ..................................... SUCCESS [  0.002 s]
[INFO] org.talend.mdm.ws .................................. SUCCESS [  6.030 s]
[INFO] org.talend.mdm.workbench ........................... SUCCESS [  3.589 s]
[INFO] org.talend.designer.routines.mdmprovider ........... SUCCESS [  0.328 s]
[INFO] org.talend.designer.routines.mdmprovider.test ...... SUCCESS [  0.093 s]
[INFO] org.talend.mdm.repository.model .................... SUCCESS [  0.849 s]
[INFO] org.talend.mdm.engines.client ...................... SUCCESS [  1.285 s]
[INFO] org.talend.mdm.workbench.serverexplorer ............ SUCCESS [  0.731 s]
[INFO] org.talend.mdm.repository .......................... SUCCESS [  2.636 s]
[INFO] org.talend.mdm.repository.test ..................... SUCCESS [  1.534 s]
[INFO] org.talend.mdm.repository.validate ................. SUCCESS [  1.435 s]
[INFO] org.talend.mdm.workbench.test ...................... SUCCESS [  0.980 s]
[INFO] org.talend.mdm.repository.validate.test ............ SUCCESS [  1.087 s]
[INFO] org.talend.mdm.tom.test.feature .................... SUCCESS [  1.015 s]
[INFO] org.talend.designer.components.tomprovider ......... SUCCESS [  0.700 s]
[INFO] org.talend.mdm.demo ................................ SUCCESS [  0.093 s]
[INFO] org.talend.mdm.ws.jars ............................. SUCCESS [  0.178 s]
[INFO] org.talend.tom.feature ............................. SUCCESS [  1.562 s]
[INFO] tos ................................................ SUCCESS [  0.002 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27:38 min
[INFO] Finished at: 2022-06-14T23:27:08-04:00
[INFO] ------------------------------------------------------------------------
[bhe@localhost work]$ 
`
